spring.application.name=Bai5

#Config datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mySql://localhost:3306/session13_bai6?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=13032006

#Config hibernate
hibernate.show-sql=true
hibernate.ddl-auto=update
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.format-sql=true
